name: Build VKOSTYA TEST

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    name: Build n deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install dependencies
        run: pip install -r req.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Run Docker Compose
        run: docker compose -f cache/docker-compose-ci.yml up -d
      
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            docker exec postgres_container pg_isready -U test && break || sleep 1
          done

      - name: Copy SQL script
        run: |
          docker cp data_insert.sql postgres_container:/var/lib/postgresql/data/data_insert.sql      

      - name: Execute SQL script
        run: |
          docker exec -i postgres_container psql -U test -d test_db -f /var/lib/postgresql/data/data_insert.sql
      
      - name: prepare for tests
        run: |
          git config --local user.email "vkostya@example.com"
          git config --local user.name "vkostya CI"
          git pull 
          git switch results

      - name: Execute PYTHON-test script
        run: |
          current_date=$(date +"%Y-%m-%d_%H-%M-%S")
          python3 cache/test_app.py | tee "results/test_results_$current_date.txt"

      - name: Generate index.html
        run: python generate_index.py
      
      - name: Commit results
        run: |
          git add -A && git commit -m "Added test results from CI/CD"
          git push

      - name: Kill environment
        run: docker compose -f cache/docker-compose-ci.yml kill