name: Build VKOSTYA TEST

on:
  push:


jobs:
  build:
    name: Build n deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Run Docker Compose
        run: docker compose -f cache/docker-compose.yml up -d
        
      - name: Kill environment
        run: docker compose kill