name: CI

on:
  schedule:
    - cron: "*/* 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
    – name: Checkout repository
      uses: actions/checkout@v2
      
    – name: Change directory
      run: cd cache

    – name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    – name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    – name: Run Docker Compose
      run: docker-compose up -d

    – name: kill env
      run: docker-compose kill